In [1]:
import numpy as np
from numpy import *
from PIL import Image
from IPython.display import display,Latex,Math
%matplotlib inline
 
from IPython.core.interactiveshell import InteractiveShell
sh = InteractiveShell.instance()
 
def number_to_str(n,cut=5):
    ns=str(n)
    format_='{0:.'+str(cut)+'f}'
    if 'e' in ns or ('.' in ns and len(ns)>cut+1):
        return format_.format(n)
    else:
        return str(n)
 
def matrix_to_latex(mat,style='bmatrix'):
    if type(mat)==np.matrixlib.defmatrix.matrix:
        mat=mat.A
    head=r'\begin{'+style+'}'
    tail=r'\end{'+style+'}'
    if len(mat.shape)==1:
        body=r'\\'.join([str(el) for el in mat])
        return head+body+tail
    elif len(mat.shape)==2:
        lines=[]
        for row in mat:
            lines.append('&'.join([number_to_str(el)  for el in row])+r'\\')
        s=head+' '.join(lines)+tail
        return s
    return None
 
sh.display_formatter.formatters['text/latex'].type_printers[np.ndarray]=matrix_to_latex


In [2]:
def initialize_v(size):
    initial=mat(np.zeros((size+1,size+1)))
    initial[int(size*(2/3)):(size+1),int(size/3)]=1
    return initial
#initializing the matrix, and the size of the matrix determines the resolution


In [3]:
def update_v(mat):
    dv=0
    v=mat
    row=shape(v)[0]
    column=shape(v)[1]
    new_v=np.mat(np.zeros((row,column)))
    for i in range(row-1):
        for j in range(column-1):
            if j==0:
                new_v[i,j]=0
            if i==row and j==0:
                new_v[i,j]=(v[i-1,j]+v[i,j+1])/2
            if i==row and j!=int(column/3) and j!=column:
                new_v[i,j]=(v[i,j-1]+v[i,j+1]+v[i-1,j])/3
            if i in range(int(row*(2/3)),row) and j==int(column/3):
                new_v[i,j]=v[i,j]
            if i in range(1,row-1) and j in range(1,column-1):
                if i!=range(int(row*(2/3)),row) and j!=int(column/3):
                    new_v[i,j]=(v[i,j-1]+v[i,j+1]+v[i-1,j]+v[i+1,j])/4
            if i in range(1,int(row*(2/3))) and j==int(column/3):
                new_v[i,j]=(v[i,j-1]+v[i,j+1]+v[i-1,j]+v[i+1,j])/4
                
    for i in range(row-1):
        for j in range(column-1):
            if abs(new_v[i,j]-v[i,j])>dv:#record the biggest difference in the matrix
                dv=abs(new_v[i,j]-v[i,j])
    return new_v,dv  #return two value, one is the new matrix, another is the difference

In [4]:
a=update_v(initialize_v(12
                       ))
for i in range(100):
    if a[1]>0.001:
        a=update_v(a[0])
b=np.delete(a[0],12,0)
b

matrix([[0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        ],
        [0.        , 0.01069642, 0.02032159, 0.02771191, 0.0323299 ,
         0.03360557, 0.03219685, 0.0284403 , 0.0235164 , 0.01774387,
         0.01187526, 0.00589367, 0.        ],
        [0.        , 0.02275032, 0.04306747, 0.05898947, 0.06834222,
         0.07100969, 0.06715437, 0.05919866, 0.04825626, 0.03644833,
         0.0240869 , 0.01202022, 0.        ],
        [0.        , 0.03742077, 0.07125613, 0.09735092, 0.11289994,
         0.11567578, 0.10844164, 0.0937261 , 0.07586156, 0.05630533,
         0.03718551, 0.01832486, 0.        ],
        [0.        , 0.05640489, 0.10767099, 0.14828609, 0.17111192,
         0.17323967, 0.15829976, 0.13443567, 0.10616296, 0.07803079,
         0.05062876, 0.02495358, 0.        ],
        [0.        , 0.08081223, 0.15635197, 0.217815  , 0.25293059,
         0.

In [5]:
a=initialize_v(3)
size(a)

16

In [6]:
b=a.flatten()
b

matrix([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0.]])

In [13]:
def matrix_update_v(mat):
    vector=mat
    dimension1=int(np.sqrt(size(vector)))
    dimension2=size(vector)
    matrix=np.mat(np.zeros((dimension2,dimension2)))
    for i in range(dimension1):
        for j in range(dimension2):
            if i==j:
                matrix[i,j]=1
    matrix[4,4]=1
    matrix[8,8]=1
    matrix[12,12]=1
    matrix[7,7]=matrix[11,11]=matrix[15,15]=matrix[9,9]=matrix[13,13]=1
    matrix[5,1]=matrix[5,4]=matrix[5,6]=matrix[6,2]=matrix[6,5]=matrix[6,7]=matrix[6,10]=matrix[10,6]=matrix[10,9]=matrix[10,11]=matrix[10,14]=0.25
    matrix[14,10]=matrix[14,13]=matrix[14,15]=1/3
            
            
    return matrix

In [14]:
matrix_update_v(b)

matrix([[1.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ],
        [0.        , 1.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 1.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , 1.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , 0.        , 1.        ,
         0.    

In [15]:

d=np.dot(matrix_update_v(b),b.T)
for i in range(100):
    d=np.dot(matrix_update_v(b),d)
d

matrix([[0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.02614379],
        [0.10457516],
        [0.        ],
        [0.        ],
        [1.        ],
        [0.39215686],
        [0.        ],
        [0.        ],
        [1.        ],
        [0.46405229],
        [0.        ]])

In [16]:
d.reshape(4,4)

matrix([[0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.02614379, 0.10457516, 0.        ],
        [0.        , 1.        , 0.39215686, 0.        ],
        [0.        , 1.        , 0.46405229, 0.        ]])

In [ ]:
def matrix_update_v2(mat):
    vector=mat
    dimension1=int(np.sqrt(size(vector)))
    dimension2=size(vector)
    matrix=np.mat(np.zeros((dimension2,dimension2)))
    for i in range(dimension1):
        for j in range(dimension2):
            if i==j:
                matrix[i,j]=1
    matrix[4,4]=1
    matrix[8,8]=1
    matrix[12,12]=1
    matrix[7,7]=matrix[11,11]=matrix[15,15]=matrix[9,9]=matrix[13,13]=1
    matrix[5,1]=matrix[5,4]=matrix[5,6]=matrix[6,2]=matrix[6,5]=matrix[6,7]=matrix[6,10]=matrix[10,6]=matrix[10,9]=matrix[10,11]=matrix[10,14]=0.25
    matrix[14,10]=matrix[14,13]=matrix[14,15]=1/3
            
            
    return matrix